Repository DogukanUrker/FlaskBlog, pull requests merged in 2025-07, with the labels that each got.

#177 Bump tamga dependency to version 1.2.0
  app/pyproject.toml
Labels: size/XS

#183 class based setting control
  app/app.py
  app/routes/about.py
  app/routes/accountSettings.py
  app/routes/adminPanel.py
  app/routes/adminPanelComments.py
  app/routes/adminPanelPosts.py
  app/routes/adminPanelUsers.py
  app/routes/category.py
  app/routes/changeLanguage.py
  app/routes/changePassword.py
  app/routes/changeProfilePicture.py
  app/routes/changeUserName.py
  app/routes/createPost.py
  app/routes/dashboard.py
  app/routes/editPost.py
  app/routes/index.py
  app/routes/login.py
  app/routes/passwordReset.py
  app/routes/post.py
  app/routes/postsAnalytics.py
  app/routes/returnPostAnalyticsData.py
  app/routes/returnPostBanner.py
  app/routes/search.py
  app/routes/setLanguage.py
  app/routes/signup.py
  app/routes/user.py
  app/routes/verifyUser.py
  app/settings.py
  app/templates/accountSettings.html
  app/utils/addPoints.py
  app/utils/beforeRequest/browserLanguage.py
  app/utils/changeUserRole.py
  app/utils/contextProcessor/isLogin.py
  app/utils/contextProcessor/isRegistration.py
  app/utils/dbChecker.py
  app/utils/delete.py
  app/utils/generateUrlIdFromPost.py
  app/utils/getAnalyticsPageData.py
  app/utils/getPostUrlIdFromPost.py
  app/utils/getProfilePicture.py
  app/utils/log.py
Labels: size/XL

#185 Update settings.py
  app/settings.py
Labels: size/XS

#186 Add authors field to pyproject.toml
  app/pyproject.toml
Labels: size/XS

#189 Fix XSS vulnerabilities and integrate safe Markdown
  app/app.py
  app/pyproject.toml
  app/routes/createPost.py
  app/routes/post.py
  app/static/css/editor.css
  app/static/css/markdown.css
  app/static/css/markdownEditor.css
  app/static/js/editor.js
  app/static/js/markdownEditor.js
  app/static/js/postConfig.js
  app/templates/adminPanelComments.html
  app/templates/components/postCardMacro.html
  app/templates/createPost.html
  app/templates/dashboard.html
  app/templates/editPost.html
  app/templates/layout.html
  app/templates/post.html
  app/templates/user.html
  app/utils/contextProcessor/markdown.py
  app/utils/markdown_renderer.py
Labels: size/XL, codex

#193 Convert category buttons to dropdown
  app/templates/category.html
  app/templates/components/categoryContainer.html
  app/templates/components/sortMenu.html
  app/templates/index.html
Labels: size/XL, codex

#194 Update forms to DaisyUI v5 components
  app/routes/editPost.py
  app/templates/changePassword.html
  app/templates/changeProfilePicture.html
  app/templates/changeUserName.html
  app/templates/components/navbar.html
  app/templates/createPost.html
  app/templates/editPost.html
  app/templates/login.html
  app/templates/passwordReset.html
  app/templates/post.html
  app/templates/searchBar.html
  app/templates/signup.html
  app/templates/verifyUser.html
Labels: size/L, codex

#196 Implement pagination for posts, admin sections and search
  app/routes/adminPanelComments.py
  app/routes/adminPanelPosts.py
  app/routes/adminPanelUsers.py
  app/routes/category.py
  app/routes/dashboard.py
  app/routes/index.py
  app/routes/search.py
  app/templates/adminPanelComments.html
  app/templates/adminPanelUsers.html
  app/templates/category.html
  app/templates/components/pagination.html
  app/templates/dashboard.html
  app/templates/index.html
  app/templates/search.html
  app/utils/paginate.py
Labels: size/L, codex

#198 refactor post editor name
  README.md
Labels: size/XS

#203 Added Hindi translation
  app/settings.py
  app/templates/changeLanguage.html
  app/translations/hi.json
Labels: size/L
